name: Update README with .cpp file count

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Count .cpp files and update README
        run: |
          COUNT=$(find . -name '*.cpp' | wc -l)
          sed -i "s/CPP_COUNT_PLACEHOLDER/${COUNT}/g" README.md

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "📈 Auto update .cpp file count"
          git push

